name: Publish Datasette

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Vercel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: |-
          datasette publish vercel country_code.db \
            --token $NOW_TOKEN \
            --project country-codes \
            --install=datasette-vega==0.6.2 \
            --install=httpx==0.17 \
            --metadata metadata.yml
